### ISSUE TITLE
Is there an issue in Jira 7.3 and python jira.search_user()?

### ISSUE THREAD

**Issue by danciarlette** [pycontribs/jira#335] opened 2017-01-26 22:52 UTC
I have a python program that ran fine on a JIRA 7.1.8 instance but now that I have upgraded to JIRA 7.3.0 the program fails to return me any users.

jira = JIRA(options=jira_options, oauth=oauth_dict)
print( "Server info: ", jira.server_info())   #this returns informat as expected.

#jira.search_users fails to return anyone.  I have >500 users.
users = jira.search_users("%")
print(users)

I get "[]"

Has there been a change in 7.3.0?

**Comment by tomashook** [comment] 2017-07-26 22:02
I have the same issue. After many tries, this works for me:
users = jira.search_users('""') , but it returns me only 1000 users and no more

**Comment by hdost** [comment] 2018-05-08 01:44
@danciarlette did you find out if there was a change in JIRA between versions?

**Comment by chevell** [comment] 2018-07-08 23:12
@danciarlette @hdost I tested this in Jira 7.0, 7.1, 7.2 and 7.3 directly (not using pycontribs/jira, just hitting the endpoints in the browser) and confirmed that this is *not a bug in pycontribs/jira*.

In Jira 7.0 and 7.1, `%` works as a wildcard in `$JIRA_BASE_URL/rest/api/2/user/search`
In Jira 7.2+, `%` is not a valid wildcard character. It is a valid string matching character, so user accounts containing this symbol will still be matched.

I can't find any public facing tickets on jira.atlassian.com that documents this change, so I'm not sure of the reason for it yet. It's possible that an underlying library's own behaviour changed, as I've seen cases where upgrading the bundled version of Tomcat or something similar would cause some edge case change in user visible behaviour. 

As a simple workaround, you can search for `.` since all users with an email address will be matched. 

Suggest closing this issue.

**Comment by hdost** [comment] 2018-07-09 17:01
As @dchevell mentioned this is not supported in JIRA 7.2+.

From Atlassian's JIRA:
> We use lucene as for our search engine. I did some research and it looks like Lucene starting at version 2.1 does support leading wild cards. You can see here via Apache's FAQ. We don't currently use this function. As you can see even Apache mentions it's an expensive operation.

https://jira.atlassian.com/browse/JRASERVER-6218

Closing

**Closed by hdost** 2018-07-09 17:01 UTC
