### ISSUE TITLE
Querying user info will break after jira gdpr changes are implemented

### ISSUE THREAD

**Issue by Plazmaz** [pycontribs/jira#771] opened 2019-03-18 20:43 UTC
After April 29th, querying user info using this library will fail. This is due to the `User` resource querying on username. Anywhere that currently uses username or userKey to query needs to also support using the account I'd or uuid.

**Comment by hdost** [comment] 2019-03-18 20:51
Duplicate of #697

**Closed by hdost** 2019-03-18 20:51 UTC
