### ISSUE TITLE
`search_issues()` breaks with JSONDecodeError or ChunkedEncodingError since v3.3.0

### ISSUE THREAD

**Issue by vfreex** [pycontribs/jira#1486] opened 2022-09-01 10:03 UTC
### Bug summary

We got the following exceptions with search_issues method:

```
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 161786 (char 161785)
```
or 
```
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

My preliminary debugging shows child class `ResilientSession` messed up some internal status in requests library and triggered an misbehavior in requests library. The first release with this issue is v3.3.0.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Jira Instance type

Jira Server or Data Center (Self-hosted)

### Jira instance version

8.20.11

### jira-python version

3.4.0

### Python Interpreter version

3.8, 3.10

### Which operating systems have you used?

- [X] Linux
- [X] macOS
- [ ] Windows

### Reproduction steps

```python
Code to reproduce this issue:


from jira import JIRA
j = JIRA(server='https://issues.redhat.com/')
query='project=OCPBUGS and issue in (OCPBUGS-522,OCPBUGS-737,OCPBUGS-433,OCPBUGS-509,OCPBUGS-727,OCPBUGS-263,OCPBUGS-756,OCPBUGS-516,OCPBUGS-306,OCPBUGS-605,OCPBUGS-429,OCPBUGS-453,OCPBUGS-515,OCPBUGS-529,OCPBUGS-688,OCPBUGS-658,OCPBUGS-465,OCPBUGS-689,OCPBUGS-744,OCPBUGS-782,OCPBUGS-783)'
j.search_issues(query, maxResults=False)
```

### Stack trace

```python
Exception has occurred: JSONDecodeError
Expecting ',' delimiter: line 1 column 141605 (char 141604)
  File "/home/dev/.local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)

During handling of the above exception, another exception occurred:

  File "/usr/lib64/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/usr/lib64/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/dev/.local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/dev/.local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
  File "/home/dev/.local/lib/python3.10/site-packages/jira/utils/__init__.py", line 74, in json_loads
    return resp.json()
  File "/home/dev/.local/lib/python3.10/site-packages/jira/client.py", line 3760, in _get_json
    raise e
  File "/home/dev/.local/lib/python3.10/site-packages/jira/client.py", line 3760, in _get_json
    raise e
  File "/home/dev/.local/lib/python3.10/site-packages/jira/client.py", line 729, in _fetch_pages
    resource = self._get_json(request_path, params=page_params, base=base)
  File "/home/dev/.local/lib/python3.10/site-packages/jira/client.py", line 3017, in search_issues
    issues = self._fetch_pages(
```

### Expected behaviour

The method returns successfully.

### Additional Context

$ pip freeze|grep jira
jira==3.4.0
$ pip freeze|grep requests
requests==2.22.0
requests-oauthlib==1.3.1
requests-toolbelt==0.9.1

Also replacing `ResilientSession` with `requests.ClientSession` can solve this issue.
Setting max_retries=0 to the constructor of `ResilientSession` doesn't solve this.

**Comment by janboll** [comment] 2022-09-02 12:23
To narrow it down further: setting maxResults to a value smaller than the total size will make the error disappear. In your example a value smaller 18

**Comment by adehad** [comment] 2022-09-04 14:54
I can confirm this behaviour on 3.3.0 and 3.4.0.

I actually believe this is fixed in the latest main however. Due to the fix here: #1471.
Are either of you able to confirm with `pip install git+https://github.com/pycontribs/jira.git@main` ?

**Comment by janboll** [comment] 2022-09-05 06:27
Thanks!, at least the example posted is now working fine!
Will give it a shot once released.

**Comment by adehad** [comment] 2022-09-05 07:45
Great, thanks for confirming.

**Comment by adehad** [comment] 2022-09-06 11:05
v3.4.1 now released, will re-open if this is still an issue.

**Closed by adehad** 2022-09-06 11:05 UTC
