### ISSUE TITLE
logout in browser when adding worklog

### ISSUE THREAD

**Issue by daroczig** [pycontribs/jira#47] opened 2015-03-12 16:51 UTC
Not sure if it is the intended behavior or am I missing something, but whenever I add a worklog via the API, I get logged out in my browser after a few minutes -- despite the fact that the "remember me" option is checked.

Example call:

```python
daroczig@********:/opt/hamster-bridge$ bin/python
Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
[GCC 4.9.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from jira import JIRA
>>> jira = JIRA('https://*********.atlassian.net', basic_auth=('*********', '*********'))
>>> jira.add_worklog('*****-21', '6m')
<JIRA Worklog: id=u'10454'>
```

Based on the [JIRA docs](https://confluence.atlassian.com/display/CLOUDKB/Getting+randomly+logged+out+of+Atlassian+Cloud), first I thought that the API calls are not re-using the session -- but that shouldn't be an issue with the Jira python library.

Any ideas on how can I debug this?

**Comment by GaretJax** [comment] 2015-03-24 11:38
This can be solved by avoiding to send session cookies along with requests to the API.

See [here](https://github.com/GaretJax/lancet/blob/f175cb2ec9a2135fb78188cf0b9f621b51d88977/lancet/jira.py#L10-L17) and [here](https://github.com/GaretJax/lancet/blob/f175cb2ec9a2135fb78188cf0b9f621b51d88977/lancet/jira.py#L24-L27) for details of how I solved it.

**Comment by kraiz** [comment] 2015-03-24 17:42
Shouldn't the jira python library taking care of this stuff. Why do we need to work around this way? Are we 2 or 3 the only ones having trouble with that logouts? Do we do anything in an unintended / unsupported way?

Sure it's easy to implement this workaround for me too (thx @GaretJax btw) but i think this should make it into the library.

Maintainers, willing to accept a PR? Maybe with a opt-in `JIRA`-contructor kwarg? Or what do you think?

**Comment by ssbarnea** [comment] 2015-03-29 15:45
I do not see how it would be possible to be logged-off from the browser because the browser and the library do not share any cookies or other data.

**Comment by ssbarnea** [comment] 2015-03-29 15:47
BTW, I will be more than happy to accept pull requests but first I would like to see a way to replicate the issue. At this moment I do not see how this would be possible unless there is a bug in jira that does not allow for more than one user session.

**Comment by GaretJax** [comment] 2015-03-29 16:19
This behavior (bug?) is not caused by having shared cookies: as you correctly pointed out, different cookies are used by the browser and the library.

The issues is caused by the JIRA session management code (server side), which logs out all active sessions for a given user if API calls with cookies are made for this very user.

You should be able to reproduce this by:
* Log into JIRA with user `A` in your browser
* Make any API calls, authenticated with the credentials of user `A` by using the library
* Wait 5 minutes
* Try to continue using JIRA in your web browser, you should be logged off.

Note that the logout after 5 minutes still happens even if you continue using JIRA in your browser immediately after the API call.

Please see this as well: https://answers.atlassian.com/questions/11465280/web-user-is-logged-out-when-using-the-rest-api it also provides code snippets to reproduce the issue.

**Comment by ssbarnea** [comment] 2015-03-29 16:42
Please try to replicate this using a standalone JIRA instance. 

The hosted version is a little bit different and Atlassian may do some weird stuff behind.

**Comment by GaretJax** [comment] 2015-03-29 17:33
Shouldn't the library work with the cloud version as well?

**Comment by ssbarnea** [comment] 2015-03-29 17:44
Yes it should but I am not willing to add workarounds for Atlassian bugs. Unless we are able to prove why you are logged out, I would only assume is a server side issue.

**Comment by GaretJax** [comment] 2015-03-29 22:52
They may fix it sooner or later (don't think there is an open issue on their side, though).

Just as a side note, even if this is a bug on Atalassian's side, the API specification does not mention the use of cookies. They are sent just because the `requests` library transparently handles that for us. Explicitly disabling them could be seen as a cleaner implementation, instead of a workaround: :-P

P.S.: Sorry, don't have a standalone instance to test ATM.

**Comment by ssbarnea** [comment] 2015-03-30 11:07
We do use cookies in other places, the python library does have some functionality where is not using REST api of JIRA because not all functions are available using REST. So, we do need to use cookies because if we disable them we will break those functions.
Still, cookies used by requests are not shared with the browser, so it would not have to affect you.

**Comment by ssbarnea** [comment] 2015-03-30 11:12
Also for automation we are always using different accounts, can't you create a special automation account in order to avoid this weird issue?

**Comment by GaretJax** [comment] 2015-03-30 11:17
I can't user different accounts because each user using the tool I
developed would need to create an additional account just for that (and as
we all know... instances are paid by the number of registered users).

I can continue to use my workaround. It works for me and is easy to
implement. This bug currently affects different projects, the solution I
presented can be implemented by them as well. Just though that it would be
nicer to have the library work out of the box.

**Comment by ssbarnea** [comment] 2015-04-01 11:05
Try the latest release as it does use requests 2.6 which adds some changes regarding cookies.

I am really busy with other assignments but I enabled Bountysource so you could try putting a bounty on this to make it happen faster.

**Comment by daroczig** [comment] 2015-04-02 00:27
Thank you @ssbarnea very much, it seems to be a lot better now -- but will report back in a few days after more testing.

**Comment by daroczig** [comment] 2015-04-02 18:44
After testing the new version of `requests` and `jira`, it seems that I'm still getting logged out from my browser really often.

I've checked Bountysource, but unfortunately it requires at least $250 for an offer expiring in 3 months, which is out of my budget -- but I would be happy to offer 25 bucks to anyone fixing this either in `jira` or @kraiz 's `hamster-bridge` in 3 months, or 50 bucks for resolving it in April. Can transfer the funds via PayPal. Thanks, Gergely

**Comment by ssbarnea** [comment] 2015-04-02 20:47
Thank you @daroczig I wasn't aware about these limitations on Bountysource, it seems that they make the service useless for many users.

Anyway, what I wanted to tell you is that I already started to implement a fix for this. It seems that problem is bigger but I will fix it during this weekend. I will also include unit test in order to be sure that it will continue to work on further versions.

**Comment by daroczig** [comment] 2015-04-03 00:28
Wow, fantastic, thank you @ssbarnea. Looking forward to test it on Monday :)

**Comment by daroczig** [comment] 2015-04-17 17:29
@ssbarnea are the changes in `0.47` related to this issue so 32f503d2d7a0c8bf1586dc9b0563b5d36d199e62 should the problem? I'd be happy to test.

**Comment by ssbarnea** [comment] 2015-04-17 19:14
Yes, please have a look. If you can try to use the trunk version.

**Comment by daroczig** [comment] 2015-04-30 16:52
Unfortunately, I still get logged out from the browser when I do `jira.add_worklog`

**Comment by ssbarnea** [comment] 2015-07-15 16:13
I closed this because there is nothing that the library does that would logout user from another session. If there is something is clearly from the server side.

**Closed** 2015-07-15 16:13 UTC

**Comment by daroczig** [comment] 2015-07-15 19:43
Sorry to hear that, as it's still annoying me a bit :(
Anyway, thank you very much for your hard work with the package, much appreciated.

**Comment by patrickjwhite** [comment] 2015-12-04 12:28
@kraiz : this is still very annoying for me, and your ObliviousCookieJar method doesn't seem to work. Did you need to change the solution at all?
