### ISSUE TITLE
Installing for local development

### ISSUE THREAD

**Issue by brianwallace** [pycontribs/jira#125] opened 2015-10-02 22:02 UTC
What is the recommended process for installing the `jira` process for local development?

I tried both `pip install -e .` and `make install` but I received the following version error:

```
python setup.py install
Traceback (most recent call last):
  File "setup.py", line 196, in <module>
    'Topic :: Internet :: WWW/HTTP',
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "build/bdist.macosx-10.9-x86_64/egg/setuptools/dist.py", line 265, in __init__
  File "build/bdist.macosx-10.9-x86_64/egg/setuptools/dist.py", line 311, in fetch_build_eggs
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources/__init__.py", line 797, in resolve
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources/__init__.py", line 1040, in best_match
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources/__init__.py", line 672, in find
pkg_resources.VersionConflict: (py 1.4.26 (/Library/Python/2.7/site-packages), Requirement.parse('py>=1.4.29'))
```

But I can't figure out where version `1.4.29` is referenced.  setup.py line 196 refers to a harmless python classifier so I am confused there as well.

Any pointers would be appreciated.  If this is a problem in my local setup, my apologies!

**Comment by ssbarnea** [comment] 2015-10-04 13:25
I will have to close this as I am not able to reproduce your problem. Tested on OS X 10.11, and I was able to install all requirements:
```
pip install -r requirements.txt
pip install -r requirements-dev.txt
pip install -r requirements-opt.txt
```

**Comment by ssbarnea** [comment] 2016-11-11 12:30
It seems that is time to reopen this and to find a way to avoid it. It seems that pytest is the culprit here. 

Other https://bugs.launchpad.net/fuel/+bug/1468201 and our own build failure at https://travis-ci.org/pycontribs/jira/jobs/175053003

I do not know exactly what versions we need to ban from requirements to avoid it.

**Comment by ssbarnea** [comment] 2017-02-07 18:04
It seems that it works ok with current version, yes the expected way to install it in dev mode is `pip install -e .`

**Closed by ssbarnea** 2017-02-07 18:04 UTC
