### ISSUE TITLE
Python3.7 reserved keyword: async

### ISSUE THREAD

**Issue by bykof** [pycontribs/jira#626] opened 2018-07-09 09:52 UTC
**Describe the bug**
The JIRA class in jira/client.py has an __init__ attribute async.
This is a reserved keyword in python3.7

**To Reproduce**
1. Install Python3.7
2. Run the library

**Stack Trace**
```
    from libs.apis.jira.jira_api import JiraAPI
  File "project/libs/apis/jira/jira_api.py", line 6, in <module>
    from jira import JIRA
  File "/Users/mbykovski/Documents/workspace/project/virtualenv/lib/python3.7/site-packages/jira/__init__.py", line 10, in <module>
    from jira.client import Comment  # noqa: E402
  File "/Users/mbykovski/Documents/workspace/project/virtualenv/lib/python3.7/site-packages/jira/client.py", line 337
    validate=False, get_server_info=True, async=False, logging=True, max_retries=3, proxies=None,
                                              ^
SyntaxError: invalid 
```

**Version Information**
Python Interpreter: 3.7
jira-python: 1.0.15
OS: OSX High Sierra

**Additional context**
Maybe just change async to asynchronous? :S

**Comment by hdost** [comment] 2018-07-09 10:34
Duplicate of #618 , fix already in master

**Closed** 2018-07-09 10:34 UTC
