### ISSUE TITLE
WARNING:root:Got recoverable error from GET 

### ISSUE THREAD

**Issue by jamesongithub** [pycontribs/jira#372] opened 2017-03-23 21:08 UTC
These retries slow down our integration tests. Any idea why? Is it concurrent auths?

```
21:05:51 WARNING:root:Got recoverable error from GET https://${ORG}.atlassian.net/rest/api/2/serverInfo, will retry [1/3] in 12.1101162796s. Err: 401 Unauthorized
21:06:03 WARNING:root:Got recoverable error from GET https://${ORG}.atlassian.net/rest/api/2/serverInfo, will retry [2/3] in 26.5554750648s. Err: 401 Unauthorized
21:06:30 WARNING:root:Got recoverable error from GET https://${ORG}.atlassian.net/rest/api/2/serverInfo, will retry [3/3] in 24.2805575368s. Err: 401 Unauthorized
```

**Comment by volym3ad** [comment] 2017-04-06 15:30
Got the same problem. In my case basic authorisation throws this error.

**Comment by Raj-Sutagatti** [comment] 2017-05-09 10:02
Getting same error as above

WARNING:root:Got recoverable error from GET https://ooyala.atlassian.net/rest/ap
i/2/serverInfo will retry [1/3] in 10.339917465499191s. Err: 401 Unauthorized

**Comment by brian-themaven** [comment] 2017-05-09 14:39
+1

**Comment by GregSharpe1** [comment] 2017-05-22 13:49
:+1: 
Having the same issue. I'm running Jira Cloud. For people hosting Jira themselves maybe this will help: https://community.atlassian.com/t5/JIRA-questions/Problem-with-authentication-to-jira-server/qaq-p/295858

**Comment by rhenter** [comment] 2017-06-28 23:23
+1

**Comment by rdu-shd** [comment] 2017-07-31 06:39
+1

**Comment by SylvainZappi** [comment] 2017-08-07 16:10
Same issue...
My python script worked fine the whole afternoon, and with no change it's now impossible to connect.
Quite annoying

**Comment by GregSharpe1** [comment] 2017-08-07 16:47
I've found a temporary fix for this issue, although it's not the best one. It works, and as I'm only using the API rarely it works just fine for me. 

The fix (using basic authentication): log in as the user your attempting to make the API call with, and change the password to the password.. honestly, I'm not sure why this fixs the issue but it's a temporary fix!

**Comment by jnsfrg** [comment] 2017-10-17 14:55
found any solution for this ? Having the same issue after updating to python 3.6.X

**Comment by nevermindr** [comment] 2017-11-07 15:43
Got the same issue.
Using basic_auth, tried both `'verify': "False"` and `'verify': "False"`.
Connecting to internally hosted JIRA:
```  
    "version": "7.2.9",
    "versionNumbers": [
        7,
        2,
        9
    ],
    "deploymentType": "Server",
    "buildNumber": 72011,
    "buildDate": "2017-05-23T00:00:00.000+0200",
```

However same request works fine in Postman with Basic Auth:
`GET /rest/api/2/project`

**Comment by hdost** [comment] 2017-11-15 21:00
Can someone give a code example which produces this, or a specific test there this is an issue?

**Comment by eltermann** [comment] 2017-11-24 15:45
Context:

Using jirashell with anonymous user:

```bash
$ jirashell -s http://jira.atlassian.com
```

After running some search queries, the described error started happening:

```
Got recoverable error from GET http://jira.atlassian.com/rest/api/2/search, will retry [2/3] in 12.9660352519s. Err: 401
```

Changing logging to DEBUG mode displays the following response content.

```html
<p>Encountered a <code>&quot;401 - Unauthorized&quot;</code> error while loading this page.</p>
<p>os_authType was &#39;any&#39; and an invalid cookie was sent.</p>
<p><a href="/secure/MyJiraHome.jspa">Go to JIRA home</a></p>
```
I believe it has to do with cookie management.

**Comment by eltermann** [comment] 2017-11-24 16:47
Just got this same error message accessing directly from browser (logged in to my account)!

URL: https://jira.atlassian.com/rest/api/2/issue/853542/changelog

![screenshot from 2017-11-24 14-42-17](https://user-images.githubusercontent.com/569111/33218750-ba58d316-d125-11e7-9235-eb6d3a4230bf.png)

Accessing from "Anonymous browsing" works fine though.

Now I believe it has to do with Jira REST itself not with jira-python-api.

**Comment by Mathkvant** [comment] 2018-01-10 11:22
I have same problem

**Comment by FergusClare** [comment] 2018-02-12 20:37
Same problem for me.


```
from jira import JIRA
import re

server = {'server' : 'https://myserveraddress.org'}
jira = JIRA(server, basic_auth=('myusername', 'mypassword'))
```
resulting error is:

```
WARNING:root:Got recoverable error from GET https://myserveraddress.org/rest/api/2/serverInfo, will retry [1/3] in 0.5469009552834114s. Err: 401 
```

This looks like a great library I would love to us, yet it doesn't appear to work.  Not seeing responses to the questions above.  Is this repo supported?

**Comment by FergusClare** [comment] 2018-02-12 22:03
I found a solution that works.  I use a one-liner and include the basic_auth before calling the options.  It looks like this:

```
from jira import JIRA
import re

jira = JIRA(basic_auth=('un', 'pwd'), options={'server':'https://myservername.org'})

**Comment by naqushab** [comment] 2018-02-14 16:55
@FergusClare No it doesn't work :(

**Comment by TLMcNulty** [comment] 2018-02-26 18:21
`from jira import JIRA

options = {'server': 'https://jira.org.com'}

jira = JIRA(options, basic_auth=('user', 'redact'))

new_issue = jira.create_issue(project='PROJID', summary='New issue from jira-python',
                              description='Look into this one', issuetype={'name': 'Task'})`

The above block generates the error for me.

**Comment by eze1981** [comment] 2018-02-27 22:13
I face this problem today using Jira Cloud. The solution was to logout from jira website, try to log in again. And you'll realize that your account is locked. Change your password and try again.

**Comment by wvrzel** [comment] 2018-03-03 09:39
I have the same problem. I use bugwarrior to import my JIRA tasks to taskwarrior, which uses this libary.

The bug seems to appear in a rather random fashion:
`DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/serverInfo HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/serverInfo, will retry [1/3] in 19.350630438882497s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/serverInfo HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/field HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/search?jql=assignee+%3D+currentUser%28%29+AND+status+%21%3D+closed&startAt=0&validateQuery=True&maxResults=-1 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-202/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-202/comment, will retry [1/3] in 7.2572736875890325s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-202/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-202/comment, will retry [2/3] in 37.39309820773451s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-202/comment HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-339/comment HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-323/comment HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-322/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-322/comment, will retry [1/3] in 16.416242059383926s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-322/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-322/comment, will retry [2/3] in 34.627424605780725s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-322/comment HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-319/comment HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-316/comment HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-315/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-315/comment, will retry [1/3] in 7.244327097631649s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-315/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-315/comment, will retry [2/3] in 31.88050784372008s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-315/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-315/comment, will retry [3/3] in 46.41958192102406s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-315/comment HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-314/comment HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-313/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-313/comment, will retry [1/3] in 4.5744873577209555s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-313/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-313/comment, will retry [2/3] in 3.7361304471605017s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-313/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-313/comment, will retry [3/3] in 45.58787180827549s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-313/comment HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-305/comment HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-239/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-239/comment, will retry [1/3] in 0.8526846269204946s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-239/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-239/comment, will retry [2/3] in 38.109879967141694s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-239/comment HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-163/comment HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-76004/comment HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-75475/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-75475/comment, will retry [1/3] in 2.0723343231331692s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-75475/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-75475/comment, will retry [2/3] in 26.50285246720889s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-75475/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-75475/comment, will retry [3/3] in 27.85587223433249s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-75475/comment HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-75077/comment HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-74867/comment HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-73631/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-73631/comment, will retry [1/3] in 2.9428589347105416s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-73631/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-73631/comment, will retry [2/3] in 1.197268044396247s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-73631/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-73631/comment, will retry [3/3] in 51.51409646823648s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-73631/comment HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-73086/comment HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-68619/comment HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-1384/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-1384/comment, will retry [1/3] in 18.865614232343933s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-1384/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-1384/comment, will retry [2/3] in 1.8372391230569862s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-1384/comment HTTP/1.1" 401 None
WARNING:root:Got recoverable error from GET https://<myJiraServer>/rest/api/latest/issue/<someProject>-1384/comment, will retry [3/3] in 10.296696353002586s. Err: 401 Unauthorized
DEBUG:urllib3.connectionpool:Resetting dropped connection: <myJiraServer>
DEBUG:urllib3.connectionpool:https://<myJiraServer>:443 "GET /rest/api/latest/issue/<someProject>-1384/comment HTTP/1.1" 401 None
ERROR:bugwarrior.services:Worker for [<myTarget>] failed: JiraError HTTP 401 url: https://<myJiraServer>/rest/api/latest/issue/<someProject>-1384/comment`

**Comment by NingZhuRedsilence** [comment] 2018-06-12 23:50
Got the same problem. I can't just change my password because I'm using my work credential for my work project. Has anyone been able to solve it?

**Comment by rajsahae** [comment] 2018-06-19 01:14
+1 for this issue. For me it happens when attempting to create a remote link

>>> pclient.add_remote_link(pissue, {'url':'https://jira.****.com/browse/PROJECT-1', 'title':'PROJECT-1', 'summary':'A test summary'}, relationship='tests')
WARNING:root:Got recoverable error from GET https://jira2.****.com/rest/applinks/latest/listApplicationlinks, will retry [1/3] in 11.3431702328s. Err: 401

**Comment by dividor** [comment] 2018-07-14 16:16
Same here, sued to work perfectly. We upgraded our Jira recently to 7.5.3, I wonder if this issue was introduced then perhaps

**Comment by hdost** [comment] 2018-07-15 13:04
Ok so I see a bunch of people here using ```
client = JIRA(server='http://...', basic_auth=...)
```
OR
```
client = JIRA(server={server:'http://...'}, basic_auth=...)
```
I think this may be a problem of documentation because it should just be

```
client = JIRA('http://...', basic_auth=...)
```

Please show me the docs which have lead to this, or can you replicate with my example?

**Comment by ssbarnea** [comment] 2018-07-15 14:53
401 is considered a recoverable error only because of old Atlassian bug that was not fixed yet  

Please read https://jira.atlassian.com/browse/JRA-41559 and comment on that ticket.

I will close this ticket because the current behaviour is on purpose in order to make the library call more reliable, even at the expense of being delayed in case your credentials are broken.

Once Atlassian would fix the bug please file a PR to remove 401 error code from the list of recoverable errors.

**Closed by ssbarnea** 2018-07-15 14:53 UTC
Labels: Type: Bug

**Comment by sainath199** [comment] 2018-08-06 07:39
got the same issue, anyone have the solution
WARNING:root:Got recoverable error from GET https://myjira.us.oracle.com/rest/api/2/serverInfo, will retry [5/5] in 31.03818161407505s. Err: HTTPSConnectionPool(host='xxxxxxxxxx', port=443): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1045)')))

**Comment by nebyark** [comment] 2018-11-07 00:17
I had the same issue, and realized my JIRA account was using SSO (via Google). [In their docs](https://confluence.atlassian.com/cloud/api-tokens-938839638.html), Atlassian states 

> If you use two-step verification to authenticate with your Atlassian Cloud site, then your script will need to use a REST API token to authenticate.

Simply creating an API token and using that instead of the password allowed my script to authenticate just fine.

**Comment by silencewy** [comment] 2018-11-07 03:59
@nebyark  Do jira account and Atlassian accout need to be the same account?
                   How to use it in the code？

**Comment by pjelar** [comment] 2019-01-03 16:52
+1

**Comment by SvenBrunk** [comment] 2019-01-25 14:44
for me the issue was that JIRA no longer accepts the username as login. Only the e-mail-address

**Comment by abhilashrao** [comment] 2019-02-21 02:31
Generate the API Token from your profile and use the below API
`curl -v https://YOUR_ORG_DOMAIN.atlassian.net --user <EMAIL_ADDRESS>:<API_TOKEN>`
Above API will generate cert. Just use the path in 
`JIRA(options{'server':<YOUR_ORD_DOMAIN.atlassian.net>,'verify':'cert/path'}`
Use the above only if your organization is using JIRA Cloud

**Comment by JamesJJ** [comment] 2019-04-18 12:50
As some above have stated, using an API token will work (for JIRA Cloud).

1. Create an API token here: [https://id.atlassian.com/manage/api-tokens](https://id.atlassian.com/manage/api-tokens)
2. Use your _email address_ as the username
3. Use the token value as the password

**Comment by jaczones** [comment] 2019-04-18 22:26
In case this helps anyone using basicauth I just had this same issue and narrowed it down to a duplicate entry in my .netrc file

**Comment by L1ghtman2k** [comment] 2019-07-01 13:14
I am getting the same error when performing basic auth on self-hosted jira.

**Comment by mjiang200102** [comment] 2019-07-15 18:15
look at this one::::!!!!
https://stackoverflow.com/questions/55699845/python-jira-401-recoverable-error-using-basic-auth

**Comment by dz-s** [comment] 2019-09-09 23:35
@JamesJJ thanks a lot!

**Comment by sampadap03** [comment] 2020-09-07 04:48
still same error
