### ISSUE TITLE
Search_issues is not returning more than 50 results

### ISSUE THREAD

**Issue by itsanjan** [pycontribs/jira#443] opened 2017-09-22 03:56 UTC
I have a loging code that pulls Jira data weekly using auto generated query from Jira API
However the **Search_issues ** method is not returning more than 50 results even after specifying 500 in argument
`UserIssueID=` `jira.search_issues(CurrentSprintJQL,0,500)`

> 
`
Query output :
[<JIRA Issue: key='IGTTV-4942', id='76858'>, <JIRA Issue: key='IGTTV-4941', id='76857'>, <JIRA Issue: key='IGTTV-4940', id='76856'>, <JIRA Issue: key='IGTTV-4939', id='76855'>, <JIRA Issue: key='IGTTV-4938', id='76854'>, <JIRA Issue: key='IGTTV-4937', id='76853'>, <JIRA Issue: key='IGTTV-4936', id='76852'>, <JIRA Issue: key='IGTTV-4935', id='76851'>, <JIRA Issue: key='IGTTV-4934', id='76850'>, <JIRA Issue: key='IGTTV-4933', id='76849'>, <JIRA Issue: key='IGTTV-4932', id='76848'>, <JIRA Issue: key='IGTTV-4931', id='76847'>, <JIRA Issue: key='IGTTV-4930', id='76707'>, <JIRA Issue: key='IGTTV-4929', id='76706'>, <JIRA Issue: key='IGTTV-4928', id='76704'>, <JIRA Issue: key='IGTTV-4927', id='76703'>, <JIRA Issue: key='IGTTV-4926', id='76702'>, <JIRA Issue: key='IGTTV-4925', id='76701'>, <JIRA Issue: key='IGTTV-4924', id='76700'>, <JIRA Issue: key='IGTTV-4923', id='76699'>, <JIRA Issue: key='IGTTV-4922', id='76698'>, <JIRA Issue: key='IGTTV-4921', id='76690'>, <JIRA Issue: key='IGTTV-4920', id='76689'>, <JIRA Issue: key='IGTTV-4919', id='76688'>, <JIRA Issue: key='IGTTV-4918', id='76687'>, <JIRA Issue: key='IGTTV-4917', id='76686'>, <JIRA Issue: key='IGTTV-4916', id='76685'>, <JIRA Issue: key='IGTTV-4915', id='76684'>, <JIRA Issue: key='IGTTV-4914', id='76683'>, <JIRA Issue: key='IGTTV-4913', id='76682'>, <JIRA Issue: key='IGTTV-4912', id='76681'>, <JIRA Issue: key='IGTTV-4911', id='76639'>, <JIRA Issue: key='IGTTV-4910', id='76638'>, <JIRA Issue: key='IGTTV-4909', id='76637'>, <JIRA Issue: key='IGTTV-4908', id='76636'>, <JIRA Issue: key='IGTTV-4907', id='76635'>, <JIRA Issue: key='IGTTV-4906', id='76634'>, <JIRA Issue: key='IGTTV-4905', id='76633'>, <JIRA Issue: key='IGTTV-4904', id='76632'>, <JIRA Issue: key='IGTTV-4903', id='76631'>, <JIRA Issue: key='IGTTV-4902', id='76629'>, <JIRA Issue: key='IGTTV-4901', id='76628'>, <JIRA Issue: key='IGTTV-4900', id='76627'>, <JIRA Issue: key='IGTTV-4899', id='76626'>, <JIRA Issue: key='IGTTV-4898', id='76625'>, <JIRA Issue: key='IGTTV-4897', id='76624'>, <JIRA Issue: key='IGTTV-4896', id='76623'>, <JIRA Issue: key='IGTTV-4895', id='76622'>, <JIRA Issue: key='IGTTV-4894', id='76621'>, <JIRA Issue: key='IGTTV-4893', id='76620'>, <JIRA Issue: key='IGTTV-4892', id='76619'>, <JIRA Issue: key='IGTTV-4891', id='76618'>, <JIRA Issue: key='IGTTV-4888', id='76615'>, <JIRA Issue: key='IGTTV-4887', id='76614'>, <JIRA Issue: key='IGTTV-4886', id='76613'>, <JIRA Issue: key='IGTTV-4885', id='76612'>, <JIRA Issue: key='IGTTV-4884', id='76611'>, <JIRA Issue: key='IGTTV-4883', id='76610'>, <JIRA Issue: key='IGTTV-4882', id='76609'>, <JIRA Issue: key='IGTTV-4881', id='76608'>, <JIRA Issue: key='IGTTV-4880', id='76607'>, <JIRA Issue: key='IGTTV-4879', id='76606'>, <JIRA Issue: key='IGTTV-4878', id='76605'>, <JIRA Issue: key='IGTTV-4877', id='76604'>, <JIRA Issue: key='IGTTV-4876', id='76603'>, <JIRA Issue: key='IGTTV-4875', id='76602'>, <JIRA Issue: key='IGTTV-4874', id='76558'>, <JIRA Issue: key='IGTTV-4873', id='76557'>, <JIRA Issue: key='IGTTV-4872', id='76556'>, <JIRA Issue: key='IGTTV-4871', id='76555'>, <JIRA Issue: key='IGTTV-4866', id='76332'>, <JIRA Issue: key='IGTTV-4865', id='76331'>, <JIRA Issue: key='IGTTV-4864', id='76330'>, <JIRA Issue: key='IGTTV-4863', id='76329'>, <JIRA Issue: key='IGTTV-4862', id='76328'>, <JIRA Issue: key='IGTTV-4861', id='76327'>, <JIRA Issue: key='IGTTV-4860', id='76326'>, <JIRA Issue: key='IGTTV-4859', id='76325'>, <JIRA Issue: key='IGTTV-4858', id='76324'>, <JIRA Issue: key='IGTTV-4857', id='76323'>, <JIRA Issue: key='IGTTV-4856', id='76322'>, <JIRA Issue: key='IGTTV-4849', id='76310'>, <JIRA Issue: key='IGTTV-4844', id='76239'>, <JIRA Issue: key='IGTTV-4806', id='76052'>, <JIRA Issue: key='IGTTV-4802', id='76034'>, <JIRA Issue: key='IGTTV-4767', id='75411'>, <JIRA Issue: key='IGTTV-4736', id='75041'>, <JIRA Issue: key='IGTTV-4678', id='74143'>, <JIRA Issue: key='IGTTV-4671', id='74116'>, <JIRA Issue: key='IGTTV-4660', id='74014'>, <JIRA Issue: key='IGTTV-4645', id='73917'>, <JIRA Issue: key='IGTTV-4422', id='71446'>, <JIRA Issue: key='IGTTV-3253', id='62205'>, <JIRA Issue: key='IGTTV-2440', id='52220'>, <JIRA Issue: key='IGTTV-2439', id='52219'>, <JIRA Issue: key='IGTTV-2423', id='52203'>, <JIRA Issue: key='IGTTV-2422', id='52202'>, <JIRA Issue: key='IGTTV-2417', id='52197'>, <JIRA Issue: key='IGTTV-2414', id='52194'>, <JIRA Issue: key='IGTTV-2412', id='52192'>]'
`

**Comment by itsanjan** [comment] 2017-09-22 03:57
This was working for me since that last 9 months

**Comment by smaisidoro** [comment] 2017-09-26 11:19
I'm currently doing something along the lines of:
```
>>> issues = jira.search_issues('...query...', maxResults=500)
>>> issues.__dict__
{'total': 143, 'startAt': 0, 'isLast': True, 'maxResults': 100}
```
isLast seems to be the erroneous here.

Whatever I specify in the maxResults it always returns max of 100. If I specify a maxResults evaluating as False (eg. 0, False), the behaviour defaults to 50 (maybe the size of the batches?)

**Comment by itsanjan** [comment] 2017-09-27 06:25
@smaisidoro Thank you for the reference to #439 . Im afraid the suggested change does not fix the issue.

**Comment by ericfrederich** [comment] 2017-09-28 14:28
I can confirm `_fetch_pages` is broken.

I have 386 users which match `'s'`.  Without specifying `maxResults` I get 50.  Specifying it to various numbers seems to work... but specifying `maxResults=False` clearly does not.

All 3 parts of this condition evaluate to `False`

```python
while not is_last and (total is None or page_start < total) and len(next_items_page) == page_size:
```

```
len(jira.search_users('s'))
50
len(jira.search_users('s', maxResults=7))
7
len(jira.search_users('s', maxResults=123))
123
len(jira.search_users('s', maxResults=False))
50
len(jira.search_users('s', maxResults=1000))
386
```

**Comment by itsanjan** [comment] 2017-10-20 10:54
Still not working out @ericfrederich

**Comment by magjac** [comment] 2017-11-14 16:39
I have the same issue. Always max 100 items. I've tried all versions down to 0.50 with the same result. Does anybody have it working for _any_ version?

**Comment by itsanjan** [comment] 2017-11-14 17:27
This bugs was first observed to occur during this years Atlassian Conf. , so i an assuming there is some API side changes affecting the paging function. 
Current workaround is to limit the MaxResults at 50 & then move from pages 0 to N, then i get consistent results in small portions. This is slower but works out.

**Comment by magjac** [comment] 2017-11-16 15:41
In the `master` branch (f7f48d759ab7a79903a682f75b864c931c09d6c5) this patch makes pagination work again when `maxResults=False`:

```diff --git a/jira/client.py b/jira/client.py
index 00065a2..da4adf6 100644
--- a/jira/client.py
+++ b/jira/client.py
@@ -408,9 +408,9 @@ class JIRA(object):
             if isinstance(resource, dict):
                 total = resource.get('total')
                 # 'isLast' is the optional key added to responses in JIRA Agile 6.7.6. So far not used in basic JIRA API.
-                is_last = resource.get('isLast', True)
                 start_at_from_response = resource.get('startAt', 0)
                 max_results_from_response = resource.get('maxResults', 1)
+                is_last = resource.get('isLast', start_at_from_response + max_results_from_response == total)
             else:
                 # if is a list
                 total = 1
```
In the `develop` branch (69fac2d1325589a37b5ab40542d1b6b2ca5ff418), pagination does not seem necessary; JIRA seems to return all issues in the first request.

**Comment by magjac** [comment] 2017-11-16 15:43
Setting `maxResults` to a number higher than 100, always gives just the first 100 in both branches.

**Comment by chevell** [comment] 2018-07-07 08:41
This is an intentional limitation in Jira, not a bug in this library. Returning large numbers of results per page uses more memory, so allowing you to return, say, 1000 results per page is just setting you up for an OutOfMemory error in your instance.

On the Jira Server side, you can modify this hard upper limit by setting `jira.search.views.default.max` in **jira-config.properties**, but as mentioned above, you shouldn't do this without being very, very certain you have the memory overhead available.

On Jira Cloud, you can't increase maxResults to arbitrary values, as confirmed in [JRACLOUD-67570](https://jira.atlassian.com/browse/JRACLOUD-67570). Again, this is to protect against abuses. 

Suggest closing this issue as not a bug.

**Closed** 2019-10-29 16:28 UTC
Labels: bug, wontfix
