### ISSUE TITLE
404 error with "search_issues"

### ISSUE THREAD

**Issue by Fr3dBear** [pycontribs/jira#229] opened 2016-06-16 15:16 UTC
I updated the jira version to: 1.0.7.dev20160607111203 for one of the scripts i was using to fix another bug issue, however i was unable to get the script to run do to a 404 issue when using the "search_issues" function.

Here is the line:
`issueList = authedJira.search_issues(jql_str="project = " + str(projectKey) + " AND issuetype = \"Feature Traceability Epic\" order by createdDate ASC",startAt=0,maxResults=False,validate_query=True,fields=None,expand=None,json_result=None)`

This line works fine in version 1.0.3 but not in 1.0.7

**Comment by oechslein** [comment] 2016-07-29 14:35
The problem is the "maxResults=False", it leads with 1.0.7 (also with the released one!) to an URL with "&maxResults=False" at the end. This results into a 404.

Example code:
from jira import JIRA

jira = JIRA('https://jira.atlassian.com')

for issue in jira.search_issues("resolution is not empty", maxResults=False):
    print issue

**Comment by oechslein** [comment] 2016-07-29 14:39
Problem is in _fetch_pages called from search_issues. parameter params has maxResults set to False, if this is cleared then code works again. Instead of 
        page_params = params.copy() if params else {}
        if startAt:
            page_params['startAt'] = startAt
        if maxResults:
            page_params['maxResults'] = maxResults
use the following (not the cleanest solution):
        page_params = params.copy() if params else {}
        if startAt:
            page_params['startAt'] = startAt
        if maxResults:
            page_params['maxResults'] = maxResults
        elif 'maxResults' in page_params:
            del page_params['maxResults']

**Comment by georgyo** [comment] 2016-11-12 22:34
@oechslein Fix is decent but partial. The code also queries Jira for a parameter called isLast which does not exist normally in Jira. This results in only one page of results being returned instead of all of them. 

See #275 for more.

**Comment by hdost** [comment] 2018-05-06 20:10
@ssbarnea Correct me if I'm wrong on this one, but as far as I can tell the change about setting `maxResults=false` was pretty intentional. 

I don't know that there will be a fix for this. There needs to be a cap on the lira side. Essentially what the API previously did was wrap up a loop which would retrieve all possible results. This is not really what an API should be designed to do. Therefore it looks like it was removed.

**Closed by hdost** 2018-05-06 20:10 UTC
