### ISSUE TITLE
UserWarning: You are running an outdated version of JIRA Python 0.50. Current version is 1.0.3.

### ISSUE THREAD

**Issue by maxandersen** [pycontribs/jira#156] opened 2015-12-20 09:13 UTC
when I run `pip install jira` as documented as the way to install I get 0.50, not 1.0.3.

How is 1.0.3 supposed to be installed ?

**Comment by eleusis** [comment] 2016-01-04 11:43
Sounds odd - `pip` should select the latest available, which is currently 1.0.3. Can you try forcing a specific version? e.g. `pip install jira==1.0.3`

**Comment by maxandersen** [comment] 2016-01-04 11:55
Yes, tried that and here is what I get:

```
pip install jira==1.0.3                                                                                                                                            ⏎
Downloading/unpacking jira==1.0.3
  Could not find a version that satisfies the requirement jira==1.0.3 (from versions: 0.1.0, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 0.25, 0.28, 0.30, 0.31, 0.32, 0.33, 0.35, 0.42, 0.43, 0.47, 0.48, 0.49, 0.50)
Cleaning up...
No distributions matching the version for jira==1.0.3
Storing complete log in /tmp/max/tmpxsIyhz
```

Looking in the log I notice it tries to lookup https://pypi.python.org/simple/jira/1.0.3 which 404's.

Can see that https://pypi.python.org/simple/jira does not list 1.0.3.

Searching for 'jira' https://pypi.python.org/pypi?%3Aaction=search&term=jira&submit=search gives me list where both jira 1.0.3 and jira 0.50 has the same weight 13.

Thus wondering if that is the cause ?

I tried removing jira completely, but I end up with the same error.

**Comment by eleusis** [comment] 2016-01-04 12:02
I've had the same thought, re: the weight.

Out of curiosity - which version of Python are you running? I'm using 2.7 here, and having no issues installing jira 1.0.3.

Also of interest: https://pypi.python.org/pypi/jira/json lists 1.0.3, but seems to only show a Python 2.7 version being available. I'm not too familiar with PyPI's packaging infrastructure, but that URL is the one checked by `client.JIRA._check_update()` which is the source of your warning.

**Comment by eleusis** [comment] 2016-01-04 12:11
Attaching a copy of the log from a successful install of 1.0.3 - this was done in a virtualenv where I had previously installed and uninstalled the package, thus having the dependencies already in place.

[pip.log.txt](https://github.com/pycontribs/jira/files/77156/pip.log.txt)

**Comment by maxandersen** [comment] 2016-01-04 14:43
I'm running Python 2.7.9 on OSX

**Comment by eleusis** [comment] 2016-01-04 15:31
OK, I'll see if I can reproduce on OSX in the next couple of days.. It's a bit late here. :)

My virtualenv was Python 2.7.9 on a relatively clean install of Debian 8.2.

**Comment by maxandersen** [comment] 2016-01-05 10:59
btw. running 

`pip install https://pypi.python.org/packages/2.7/j/jira/jira-1.0.3-py2.py3-none-any.whl`

seem to have worked.

**Comment by eleusis** [comment] 2016-01-05 17:03
Good workaround - I'm still curious about the root cause of the original issue though. I'll update if I find anything.

**Comment by eleusis** [comment] 2016-01-07 15:58
I haven't been able to reproduce this on OS X, using Python 2.7.10 (Apple build). Steps taken:
```
easy_install --upgrade pip
easy_install --upgrade virtualenv
# After activating virtualenv:
pip install jira
```

`pip` successfully installed the jira module in the virtual env. Versions involved:
- OS X 10.10.5
- Python 2.7.10
- pip 7.1.2
- virtualenv 13.1.2
- jira 1.0.3

Terminal snippet:
```
Successfully installed jira-1.0.3 oauthlib-1.0.3 requests-2.9.1 requests-oauthlib-0.6.0 requests-toolbelt-0.5.1 six-1.10.0 tlslite-0.4.9
(venv)dharma:venv sham$ python
Python 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jira
>>> jira
<module 'jira' from '/private/tmp/venv/lib/python2.7/site-packages/jira/__init__.pyc'>
```

**Comment by jrbenito** [comment] 2016-04-25 17:37
http://stackoverflow.com/questions/36847031/python-jira-is-not-upgraded-by-pip

same, now happening between 1.0.3 and 1.0.6

**Comment by ssbarnea** [comment] 2016-05-01 16:14
It should not happen now, I am closing it but we will reopen if necessary. Also, if someone wants to make a PR that adds an optional parameter for disabling the old version check I will merge it. Please note that that the default (not specified) should be to check if the version is outdated. pip project does the same.

**Closed by ssbarnea** 2016-05-01 16:14 UTC
Labels: ready

**Comment by hntd187** [comment] 2016-07-14 16:22
This still happens with the current 1.0.7 dev version

```
/usr/local/lib/python2.7/dist-packages/jira/client.py:282: UserWarning: You are running an outdated version of JIRA Python 1.0.3. Current version is 1.0.7.dev20160607111203. Do not file any bugs against older versions.
  __version__, released_version))
```

All I did was install via `sudo -H pip install jira`

**Comment by hntd187** [comment] 2016-07-14 16:30
Actually uninstalling and reinstalling it based on the above, it still doesn't surpress the error. 

```/home/scarman/.local/lib/python2.7/site-packages/jira/client.py:328: UserWarning: You are running an outdated version of JIRA Python 1.0.7. Current version is 1.0.7.dev20160607111203. Do not file any bugs against older versions.
  __version__, released_version))```

via ```pip install --user https://pypi.python.org/packages/13/28/7c3030c78ad2a5a8e1805db1ab1632b43f41fd7b646c585b85a280cafa4b/jira-1.0.7.dev20160607111203-py2.py3-none-any.whl```
