### ISSUE TITLE
pypi has a 1.0.3 whl package but not the associated tarball, so I still get 0.50 version for install

### ISSUE THREAD

**Issue by rickbradshaw** [pycontribs/jira#161] opened 2016-01-05 20:22 UTC
I am using "fpm" to build rpms from your PyPi project, but fpm seems to think that .50 is the latest available, so I took a look at the debug output and it showed that it was using this link: 

https://pypi.python.org/simple/jira/

when I go there I see the 1.0.3.whl package but there is no associated 1.0.3.tar.gz. Can you upload a tarball for the 1.0.3?

**Comment by eleusis** [comment] 2016-01-05 23:26
This is a duplicate of #156.

**Closed** 2016-05-01 16:30 UTC
Labels: ready
