### ISSUE TITLE
`async` is a reserved keyword on Python 3.7

### ISSUE THREAD

**Issue by gordonshieh94** [pycontribs/jira#603] opened 2018-06-28 23:19 UTC
**Describe the bug**
Keyword arguments that are named `async` now conflicts with the reserved keyword of the same name, introduced in Python 3.7.

**To Reproduce**
In a Py3.7 interpreter with jira installed:
```
from jira.client import Comment  
```

**Stack Trace**
Error I got from tox while running unit tests in our CI
```
    from jira.client import Comment  # noqa: E402
E     File "/tmp/.tox/py37-linux/lib/python3.7/site-packages/jira/client.py", line 225
E       validate=False, get_server_info=True, async=False, logging=True, max_retries=3, proxies=None,
E                                                 ^
E   SyntaxError: invalid syntax
```

**Version Information**
Python Interpreter: 3.7.0
jira-python: 1.0.14
OS: any

**Comment by hdost** [comment] 2018-06-29 01:15
Duplicate of #397

**Closed** 2018-07-03 08:40 UTC
Labels: SemVer: breaking-change, Type: Bug
