### ISSUE TITLE
Upload sources to pypi?

### ISSUE THREAD

**Issue by ralphbean** [pycontribs/jira#198] opened 2016-05-10 16:53 UTC
Thanks for the great project, btw.  :)

In the latest release, (1.0.3) only the built binary wheel is on pypi.

Could you include the .tar.gz sources as well in the next release?

**Comment by naphthalene** [comment] 2016-05-19 19:29
This is causing me grief, because it fails to easy install:

```
> easy_install jira==1.0.3                                                                                             
Searching for jira==1.0.3
Reading <snip>
No local packages or download links found for jira==1.0.3
error: Could not find suitable distribution for Requirement.parse('jira==1.0.3')
```

**Comment by Duologic** [comment] 2016-05-24 20:37
Duplicate of https://github.com/pycontribs/jira/issues/127

**Closed** 2017-02-07 18:05 UTC
