### ISSUE TITLE
Getting the context of custom fields

### ISSUE THREAD

**Issue by qequ** [pycontribs/jira#1654] opened 2023-05-02 19:59 UTC
### Problem trying to solve

Is there a way to have the list of values a field (custom field in my case) can have?

### Additional Context

Using the `issue` only returns data of the issue, not in general

**Comment by Keenpachi** [comment] 2023-05-05 15:04
you can get this with requests library as described -> 

https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-custom-field-contexts/#api-group-issue-custom-field-contexts

I don't see that this was implemented inside jira library.

**Comment by studioj** [comment] 2023-05-16 21:40
@qequ @Keenpachi thank you for reporting.
We're open to PR's which could "fix" this feature request.
Don't forget to add a test and excuse us for late responses.
Kind Regards

**Comment by studioj** [comment] 2023-05-19 18:28
@qequ I'm closing this as it seems to be a duplicate of this one
https://github.com/pycontribs/jira/issues/1619
please reopen if thats not the case

**Closed by studioj** 2023-05-19 18:28 UTC
Labels: duplicate, feature

**Comment by qequ** [comment] 2023-05-24 20:24
@studioj  is still possible to make a pull request with this feature or will it continue as a workaround ?

**Comment by studioj** [comment] 2023-05-25 06:03
Sure, is the other ticket an ok duplicate?
